targets:
  $default:
    builders:
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: api_management|lib/schema.graphql
          type_overrides:
            UI:
              name: String
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: api_management|lib/schema.graphql
          type_overrides:
            UI:
              name: String
          custom_serializers:
            - import: "package:api_management/src/scalars/ui_string_serializer.dart"
              name: UIStringSerializer
